version: '3.8'

services:
  next:
    tty: true
    build: ./
    image: gaatha-next
    command: sh -c 'yarn install && yarn dev'
    environment:
      GRAPHQL_CODEGEN_ENDPOINT: ${GRAPHQL_CODEGEN_ENDPOINT:-http://server:8020/graphql/}
      NEXT_APP_GRAPHQL_ENDPOINT: ${NEXT_APP_GRAPHQL_ENDPOINT:-http://server:8020/graphql/}

    volumes:
      - .:/code
    ports:
      - '3020:3020'

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    restart: unless-stopped
    image: gaatha-server/server
    build:
      context: ./server/
    tty: true
    environment:
      DEBUG: ${DEBUG:-True}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-?}
      DB_NAME: ${DB_NAME:-postgres}
      DB_USER: ${DB_USER:-postgres}
      DB_PWD: ${DB_PWD:-postgres}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      LANGUAGE_CODE: ${LANGUAGE_CODE:-en-us}
      TIME_ZONE: ${TIME_ZONE:-UTC}
    command: bash -c "/code/scripts/run_develop.sh"
    volumes:
      - ./server/:/code
      - media:/media
    ports:
      - '8020:8020'
    depends_on:
      - db

volumes:
  media:
  postgres-data:
