version: '3.8'


x-next: &base_next_setup
  tty: true
  build: ./
  image: gaatha-next
  environment:
    NEXT_APP_GRAPHQL_ENDPOINT: ${NEXT_APP_GRAPHQL_ENDPOINT:-http://gaatha-server:8020/graphql/}
  volumes:
    - .:/code


services:
  next:
    <<: *base_next_setup
    command: sh -c 'yarn install && yarn dev'
    ports:
      - '3020:3020'
    depends_on:
      - gaatha-server

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  gaatha-server:
    restart: unless-stopped
    image: gaatha-server/server
    build:
      context: ./server/
    tty: true
    environment:
      DEBUG: ${DEBUG:-True}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-?}
      DB_NAME: ${DB_NAME:-postgres}
      DB_USER: ${DB_USER:-postgres}
      DB_PWD: ${DB_PWD:-postgres}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      LANGUAGE_CODE: ${LANGUAGE_CODE:-en-us}
      TIME_ZONE: ${TIME_ZONE:-UTC}
    command: bash -c "/code/scripts/run_develop.sh"
    volumes:
      - ./server/:/code
      - media:/media
    ports:
      - '8020:8020'
    depends_on:
      - db

  checks:
    <<: *base_next_setup
    command: sh -c 'pre-commit run -vvv --all-files'
    profiles:
      - test

volumes:
  media:
  postgres-data:
