name: CI

on:
  pull_request:
  push:
    branches:
      - 'develop'

env:
  GITHUB_WORKFLOW: true

jobs:
  ci:
    name: Lint + Type Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          cache: 'yarn'

      # Pre-commit
      - uses: actions/setup-python@v4
      - name: Install pre-commit
        run: pip install pre-commit

      - name: Pull submodules (Server)
        env:
          SSH_KEY_FOR_SUBMODULE: ${{secrets.GH_GAATHA_SERVER_SSH_KEY}}
        # TODO: Use depth 1 for git submodule update if not already
        run: |
          mkdir $HOME/.ssh &&
          echo "$SSH_KEY_FOR_SUBMODULE" > $HOME/.ssh/id_rsa &&
          chmod 600 $HOME/.ssh/id_rsa &&
          git submodule update --init --recursive

      - name: Install dependencies
        run: yarn install --prefer-online

      - name: Yarn generate
        run: yarn generate

      - name: Check
        run: pre-commit run -vvv --all-files

     # - name: Build
     #   run: yarn export
