name: CI

on:
  pull_request:
  push:
    branches:
      - 'develop'

env:
  GITHUB_WORKFLOW: true

jobs:
  ci:
    name: Lint + Type Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Pull submodules (Server)
        env:
          SSH_KEY_FOR_SUBMODULE: ${{secrets.GH_GAATHA_SERVER_SSH_KEY}}
        run: |
          mkdir $HOME/.ssh &&
          echo "$SSH_KEY_FOR_SUBMODULE" > $HOME/.ssh/id_rsa &&
          chmod 600 $HOME/.ssh/id_rsa &&
          git submodule update --init --recursive

      - name: Install dependencies
        run: yarn install --prefer-online

      - name: Check unused files
        id: unused_files
        continue-on-error: true
        run: yarn generate && yarn check-unused

      - name: Lint
        continue-on-error: true
        id: js_lint
        run: yarn generate && yarn lint

      - name: Css Lint
        continue-on-error: true
        id: css_lint
        run: yarn css-lint

      - name: Typecheck
        continue-on-error: true
        id: typecheck
        run: yarn generate && yarn typecheck

      - name: Check on failures
        if: steps.unused_files.outcome != 'success' || steps.js_lint.outcome != 'success' || steps.css_lint.outcome != 'success' || steps.typecheck.outcome != 'success'
        run: exit 1

     # - name: Build
     #   run: yarn export
